### ISSUE TITLE
[Bug] Farmer software cards are continuously refreshed

### ISSUE THREAD

**Issue by kuhnbv** [DKE-Data/agrirouter#15] opened 2024-07-26 10:17 UTC
### What happened?

In the new agrirouter farmer UI, the software cards seems to be refreshing all the times, making the icons nearly impossible to click.

My browser is continuously making requests to the following api routes:
- GET `https://application-service.qa.agrirouter.farm/applications/{guid}`
- GET `https://account-service.qa.agrirouter.farm/preference`

In this example, I can't click any icons on the `IO tool` and `Kuhn EasyTransfer` cards, and my browser made more than 700 requests in under 30s.

![image](https://github.com/user-attachments/assets/418a3b76-22eb-4cfc-9216-4c76b9ea5804)

Tested with Firefox 128.0 and Edge 126.0.2592.113.

### agrirouter SDK

No SDK

**Comment by saschadoemer** [comment] 2024-07-26 19:07
Same for me 👍🏼

**Comment by oliverrahner** [comment] 2024-08-02 13:41
I have received one additional report of this issue

**Comment by AlexisZankowitch** [comment] 2024-08-02 14:38
I would need more information sadly because we can't replicate the issue or our company network neither on personal networks. 

Does the issue occurs only while visiting the farmer page? 

Could you provide me the email of your account so I can impersonate your users and see how the app behaves in that case?

**Comment by kuhnbv** [comment] 2024-08-02 14:55
> I would need more information sadly because we can't replicate the issue or our company network neither on personal networks.
> 
> Does the issue occurs only while visiting the farmer page?
> 
> Could you provide me the email of your account so I can impersonate your users and see how the app behaves in that case?

Yes the farmer pages, and more precisely the software cards. The flickering is not really visible at first glance, but can be made more visible hovering the info or edit icons. No icons react to mouse clicks unless spammed.
The account email is `dev_agrirouter@kuhn.com`.

**Comment by AlexisZankowitch** [comment] 2024-08-05 07:42
Good news, I am able to also see the issue while impersonating one of your users. I will see what's happening locally so I can add some log statements. 

I hope I will come back to you with more good news later today about that issue.

**Comment by AlexisZankowitch** [comment] 2024-08-05 16:04
I was able to find the issue. There is a PR created. As soon as we merge it I will update the frontend to bring it to QA. 

Meanwhile I can create routes if necessary for your endpoints.

**Comment by AlexisZankowitch** [comment] 2024-08-07 11:27
It took a bit more time but the fix should be available soon.

**Comment by AlexisZankowitch** [comment] 2024-08-08 08:03
I deployed the fix on QA. I checked with dev_agrirouter@kuhn.com, agrirouter-developer@logineko.com. I was able to open the details page, and click on the other buttons. 

@kuhnbv, @saschadoemer  Could you let me know if the issue is also fixed on your side?

**Comment by kuhnbv** [comment] 2024-08-08 08:13
> I deployed the fix on QA. I checked with [dev_agrirouter@kuhn.com](mailto:dev_agrirouter@kuhn.com), [agrirouter-developer@logineko.com](mailto:agrirouter-developer@logineko.com). I was able to open the details page, and click on the other buttons.
> 
> @kuhnbv, @saschadoemer Could you let me know if the issue is also fixed on your side?

The issues seems to be fixed for me, thanks!

But the fix seems to have introduced another bug (less annoying, but I want to let you know 😄): the last software card is duplicated.

![image](https://github.com/user-attachments/assets/5afa2e87-05e7-42e6-bed0-79a9a56f268f)

Also tested on Firefox and Edge.

Should I open another bug report?

**Comment by saschadoemer** [comment] 2024-08-08 09:05
@AlexisZankowitch fixed for me 👍🏼

**Comment by AlexisZankowitch** [comment] 2024-08-08 14:24
@kuhnbv I've just pushed a fix for your issue. I will then close this ticket. Thank you for your feedback :)

**Closed as completed by AlexisZankowitch** 2024-08-08 14:24 UTC
Labels: bug
