### ISSUE TITLE
[Bug] Random client ID leads to rejected MQTT connection

### ISSUE THREAD

**Issue by saschadoemer** [DKE-Data/agrirouter#16] opened 2024-07-26 19:13 UTC
### What happened?

In the former implementation of the agrirouter it was possible to use a random client ID, if you want to connect to the gateway.

![image](https://github.com/user-attachments/assets/43fa729f-decd-42f5-bb96-4b4f97d31c42) 

https://github.com/agrirouter-middleware/agrirouter-middleware/blob/bf6d87322fdf26188c82ea9f6cb6a6e1550122ab/agrirouter-middleware-integration/src/main/java/de/agrirouter/middleware/integration/mqtt/MqttClientManagementService.java#L171

This has been very helpful to avoid connection loss, if a router device was used in multiple environments. I.e. a developer uses the production router device locally to test something. In this case, the connection on the production environment was dropped. 

It is easy to fix for the application, of course. 

![image](https://github.com/user-attachments/assets/d9cd8e37-5c32-4147-8bb1-36ed55283c04)

We need to be sure, that this problem will not be a problem of other customers, since I do not know how many
developers used this workaround to avoid connection stealing.

### agrirouter SDK

Java

**Comment by oliverrahner** [comment] 2024-07-29 09:36
This is by design, as we are tying all permissions of a router device to its client ID, as per the MQTT spec.
The connection stealing issue should be fixed by creating distinct router devices.
A random client ID was never _officially_ supported, so it technically isn't part of the backwards compatibility scope.
We will, however, explicitly monitor connections with wrong client IDs so we can proactively inform developers/application owners about this issue.

**Comment by AlexisZankowitch** [comment] 2024-08-09 09:31
We will close this discussion because there won't be any additional action on this matter

**Closed as completed by AlexisZankowitch** 2024-08-09 09:31 UTC
Labels: bug
