### ISSUE TITLE
[Bug] Team set context id not forwarded with push notification

### ISSUE THREAD

**Issue by AlexisZankowitch** [DKE-Data/agrirouter#22] opened 2024-08-07 12:08 UTC
### What happened?

Krone is receiving routed messages via push notification. 

It looks like the `team set context id` is left blank when the routed message arrives via push notification

### agrirouter SDK

No SDK

**Comment by oliverrahner** [comment] 2024-08-07 15:10
duplicate of #5

**Closed as completed by oliverrahner** 2024-08-07 15:10 UTC
Labels: bug
