### ISSUE TITLE
[Known Issue] Team set context id not forwarded

### ISSUE THREAD

**Issue by AlexisZankowitch** [DKE-Data/agrirouter#5] opened 2024-07-01 07:32 UTC
When sending device description the team set context Id is not always part of the message sent to the receiver endpoints

**Comment by doekermk** [comment] 2024-08-06 12:22
@oliverrahner @AlexisZankowitch it looks like the _team set context id_ is only missing in the push notification. See log of the IO-Tool. First it received the push notification with missing _team set context id_. After requesting the messages itself the log does not contain any error.

![image](https://github.com/user-attachments/assets/1980629e-d02f-4f45-b872-ec6ceddd21bd)

**Comment by oliverrahner** [comment] 2024-08-08 10:22
The assumed fix for this has been deployed to QA. We're still testing ourselves, but please feel free to test on your end as well.

**Comment by oliverrahner** [comment] 2024-08-09 06:51
We received some notes that the issue is indeed solves, closing now.

**Closed as completed by oliverrahner** 2024-08-09 06:51 UTC
Labels: known issue
